<?php

/**
 * @file
 * Create contact forms.
 */

/**

/**
 * Implements hook_menu().
 */
function discoverajob_contact_menu() {
  $items['contacts'] = array(
    'title' => 'Contact',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('discoverajob_contact_form'),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'discoverajob_contact.pages.inc',
  );
  return $items;
}
